Exemplo de consulta por nome de filme
{
  getMovieByName(name: "Matrix"){
    createdAt
    name
    genre
    country
    language
  }
}

Exemplo de Mutation User
mutation {
  createUser(data: {name: "Teste"}) {
    name
  }
}


Exemplo de getOscar
{
  getAwards(id: "036a9e14-51da-4a92-af67-6bc4ec938495") {
    idMovie
    oscar
  }
}

Exemplo de Mutation Movie
mutation {
  createMovie(data: {name: "Madagascar", genre: COMMEDY, country: "EUA" language: PORTURGUESE, money: 19.9} ) {
    name
  }
}