Exemplo de consulta por nome de filme
{
  getMovieByName(name: "Matrix"){
    createdAt
    name
    genre
    country
    language
  }
}

Exemplo de Mutation
mutation {
  createUser(data: {name: "Teste"}) {
    name
  }
}